name: flutter_marketing_app
publish_to: 'none'
description: Avenor native marketing app for attendance, on-hand products, offline sales, and product knowledge.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_local_notifications: ^17.2.4
  geolocator: ^13.0.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avenor_hitam.png
